### ISSUE TITLE
Fetching from pull/%d/head during the webhook can return stale data

### ISSUE THREAD

**Issue by jdm** [servo-automation/upstream-wpt-sync-webhook#11]
https://github.com/servo/servo/pull/20329 shows errors like:
```
root@servo-master1:~# cat /home/wpt-sync/upstream-wpt-sync-webhook/error-snapshot-1521387016450/exception
Traceback (most recent call last):
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 441, in process_and_run_steps
    step.run(config)
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 317, in run
    commits = _fetch_upstreamable_commits(config, self.pull_request, self.fetch_action)
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 335, in _fetch_upstreamable_commits
    diff = get_filtered_diff(config['servo_path'], commit['sha'])
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 77, in get_filtered_diff
    cwd=path)
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 71, in git
    raise e
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 67, in git
    out = subprocess.check_output(command_line, cwd=kwargs['cwd'], env=kwargs.get('env', {}))
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['git', 'show', '--binary', '--format=%b', '6ca5e953f70f4d53457beb14847654e649296e7f', '--', 'tests/wpt/web-platform-tests/']' returned non-zero exit status 128
```
The error changes each time as new commits are added, since the existing commits are available the next time the sync happens, but the newest commits aren't present yet.

**Comment by jdm** [comment]
This appears to be fixed by bbf26bffd6115ac355f255b1ea09ca652f6a6971.
