### ISSUE TITLE
Removing individual labels did not work as expected

### ISSUE THREAD

**Issue by jdm** [servo-automation/upstream-wpt-sync-webhook#23]
From https://github.com/servo/servo/pull/23073#issuecomment-475825416, the exception was:
```
Traceback (most recent call last):
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 469, in process_and_run_steps
    step.run(config)
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 213, in run
    _merge_upstream_pr(config, self.upstream)
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 220, in _merge_upstream_pr
    remove_upstream_pr_label(config, 'do not merge yet', str(upstream))
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 234, in remove_upstream_pr_label
    (config['upstream_org'], pr_number, label)))
  File "/home/wpt-sync/upstream-wpt-sync-webhook/_venv/lib/python3.4/site-packages/upstream_wpt_webhook/sync.py", line 60, in authenticated
    raise ValueError('got unexpected %d response: %s' % (response.status_code, response.text))
ValueError: got unexpected 404 response: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/labels/#remove-a-label-from-an-issue"}
```

cc @CYBAI

**Comment by jdm** [comment]
[This URL](https://github.com/servo-automation/upstream-wpt-sync-webhook/blob/71b6ac8adcbfa0f7c26c180ccc388f0599a8718e/upstream_wpt_webhook/sync.py#L233) looks wrong to me - it seems to be targeting a repo named `test` instead of `web-platform-tests`.

**Comment by jdm** [comment]
Fixed by https://github.com/servo-automation/upstream-wpt-sync-webhook/commit/b007f4fe04c476d82178d63344555e6705afc192.

**Comment by CYBAI** [comment]
Sorry that I missed to change it back 😭 That was my testing repo 🤦‍♂️ and thanks for fixing it!

**Comment by CYBAI** [comment]
Btw, if there's wpt sync error, can I check the error log on buildbot?

**Comment by jdm** [comment]
Right now I log into servo-master1 to view the ogs, but I think we could safely add the exception to the GitHub comment.

**Comment by CYBAI** [comment]
> Right now I log into servo-master1 to view the logs

Thanks! But it seems I can't see `servo-master1` in [Buildslaves](https://build.servo.org/buildslaves) page 👀

> but I think we could safely add the exception to the GitHub comment.

Sounds good to me! Let me file an issue for it!
